apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment3
  name: deployment3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment3
  strategy: {}
  template:
    metadata:
      labels:
        app: deployment3
    spec:
      containers:
      - name: container1
        image: busybox
        command:
          - 'sleep'
          - '3600'
        resources: 
          requests:
            cpu: 50m
            memory: 4Mi
          limits:
            cpu: 250m
            memory: 64Mi
      volumes:
        - name: test-pvc
          persistentVolumeClaim:
            claimName: test-pvc
status: {}
