apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-storage-metrics
rules:
- apiGroups:
    - ""
  resources: 
    - pods
    - nodes
    - persistentvolumes
    - persistentvolumeclaims
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - nodes/proxy
  verbs:
    - get