apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-storage-metrics
rules:
- apiGroups:
    - ""
  resources: 
    - nodes
  verbs:
    - get
- apiGroups:
    - ""
  resources:
    - nodes/proxy
  verbs:
    - get