apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubernetes-storage-metrics
spec:
  selector:
    matchLabels:
      app: kubernetes-storage-metrics
  template:
    metadata:
      labels:
        app: kubernetes-storage-metrics
    spec:
      serviceAccountName: kubernetes-storage-metrics
      containers:
      - name: kubernetes-storage-metrics
        image: quay.io/cloud-for-you/kubernetes-storage-metrics:main
        #image: nicolaka/netshoot:latest
        #imagePullPolicy: Always
        #command: ["/bin/sh", "-c"]
        #args:
        #  - |
        #    echo "Starting kubernetes-storage-metrics container";
        #    echo "Node Name: ${CURRENT_NODE_NAME}";
        #    echo "Scrape Interval: ${SCRAPE_INTERVAL}s";
        #    while true; do
        #      echo "Collecting metrics...";
        #      sleep ${SCRAPE_INTERVAL};
        #    done;
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: CURRENT_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SCRAPE_INTERVAL
          value: "30"
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi