name: Semantic
on:
  workflow_dispatch: {}

jobs:
  semantic:
    name: check required steps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Get modified project.yaml
        id: metadata
        run: |
          files_changed=$(git show --pretty="" --name-only)
          version_bumps=$(echo "$files_changed" | grep project.yaml | xargs git show | grep -c "+version" || true)
          if [[ "$version_bumps" -qe 1 ]]; then
            echo "::error file=project.yaml,title=Detect change version::Detected changes in file without version bump in package.yaml"
            exit 1
          fi
